name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      attendee-name:
        description: The name of attendee (name-surname)
        required: true
      environment:
        description: The target environment
        required: true
        type: choice
        options:
          - stage
          - prod

jobs:
  get-global-secret-token:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      global-secret-token: ${{ steps.global-secret-token.outputs.value }}
    steps:
      - name: Define global-token-secret based on environment
        uses: dkershner6/switch-case-action@v1
        id: global-secret-token
        with:
          default: GLOBAL_SECRET_TOKEN_STAGE
          conditionals-with-values: |
            ${{ github.event.inputs.environment == 'prod' }} => GLOBAL_SECRET_TOKEN_PROD

  call-local-workflow:
    needs: get-global-secret-token
    uses: ./.github/workflows/call-me-i-am-reusable.yml
    with:
      attendee-name: ${{ github.event.inputs.attendee-name }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      super-secret-token: ${{ needs.get-global-secret-token.outputs.global-secret-token }}

  print-the-message:
    needs: call-local-workflow
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Print the message received from the called workflow
        run: echo ${{ needs.call-local-workflow.outputs.formatted-message }}
